services:
  chroma:
    container_name: chroma_ferriatienda

    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma
    restart: always

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   healthcheck:
  #     test: curl -s http://localhost:9200 || exit 1
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  postgres:
    image: postgres:15
    container_name: postgres_ferriatienda
    restart: always
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ferriatienda_app:
    build: .
    container_name: ferriatienda_app
    #depends_on: database 
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface # Cache for Hugging Face models
    command: poetry run streamlit run ferriatienda/streamlit_app.py

volumes:
  chroma_data:
  postgres_data:

# networks:
#   projet_fil_rouge_default: