services:
  chroma:
    container_name: chroma_ferriatienda
    image: chromadb/chroma:1.0.12
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chroma   # <- server persistence
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  ferriatienda_app:
    build: .
    container_name: ferriatienda_app
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    depends_on:
      - chroma
      - ollama
      - postgres
    command: poetry run streamlit run ferriatienda/streamlit_app.py
  
    # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
  #   container_name: elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  #   healthcheck:
  #     test: curl -s http://localhost:9200 || exit 1
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  postgres:
    image: postgres:15
    container_name: postgres_ferriatienda
    restart: always
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  chroma_data:
  ollama_data:
  postgres_data:




