[tool.poetry]
name = "ferriatienda"
version = "0.1.0"
description = "Chatbot and AI agent for Ferritienda"
authors = ["dianasolangel <dianasolangelfh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
requests = "^2.31.0"
pandas = "^2.1.1"
numpy = "^2.2.3"
matplotlib = "^3.7.2"
streamlit = "^1.42.2"
scikit-learn = "^1.6.1"
beautifulsoup4 = "^4.13.3"
lxml = "^5.3.1"
selenium = "^4.12.0"
pytesseract = "^0.3.10"
pdf2image = "^1.16.3"
Pillow = "^9.3.0"
ipykernel = "^6.29.5"
jupyter = "^1.1.1"
fake-useragent = "^2.0.3"
webdriver-manager = "^4.0.2"
python-dotenv = "^1.0.1"
dotenv = "^0.9.9"
transformers = "^4.52.4"
langchain = "^0.3.25"
huggingface-hub = ">=0.32.4,<0.35.0"
langchain-huggingface = ">=0.2.0,<0.4.0"
faiss-cpu = "^1.11.0"
elasticsearch = "^8.12.1"
chromadb = "^1.0.12"
accelerate = "^1.7.0"
sentence-transformers = "^4.1.0"
langchain-community = "^0.3.24"
langchain-chroma = "^0.2.4"
sqlalchemy = "^2.0"
psycopg2-binary = "^2.9"
langchain-core = "^0.3.74"
langchain-ollama = "^0.3.6"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"
pytest = "^8.3.4"
flake8 = "7.1.2"
black = "25.1.0"
mypy = "^1.5.1"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"